### ISSUE TITLE
Error in recognizing inequality as "tag".

### ISSUE THREAD

**Issue by nusgnojkrap** [OldBlackJoe/mybatis-mapper#13]
Hi, I am a user using Mybartis.
An unexpected error occurred while using "Mybatis" and found the following errors.

```ts
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
</mapper>
<mapper namespace="errorexample">
<select id="errorSql">
SELECT VNS_IDX
FROM
TB_VNS_IBIZ_NUMBER
WHERE
VNS_NUMBER <= #{vnsNumber} and VNS_NUMBER >= #{vnsNumber} 
</select>
</mapper>

```

In the above sql statement, when inequality ex) "<", ">" is used, there is an error in recognizing it as tag.

The code above is an example.

Later, as a result of looking a little further, it was predicted that the error occurred in "html-parse-stringfy2" used by "Mybatis."

**Comment by OldBlackJoe** [comment]
Yes, as you said, I solved this problem by upgrading the dependent package version.
Please use version 0.6.6. Thanks for raising the issue.
