### ISSUE TITLE
Query with an apostrophe results in an error

### ISSUE THREAD

**Issue by mavridiSS** [OldBlackJoe/mybatis-mapper#14]
Trying to query with an apostrophe is throwing an error: `SQL0010N  The string constant beginning with "'))" does not have an ending string delimiter.  SQLSTATE=42603`

Setup:
`getStatement('test', 'statement', {'name': "broken'string"},  { language: 'db2', indent: '  ' })`
Mapper:
`<mapper namespace="test">
  <select id="statement">
      SELECT * FROM TABLE t 
      WHERE t.property > 0
      <if test="name != null>
        AND UPPER(t.name) LIKE UPPER(#{name})
      </if>
  </select>
</mapper>`

https://github.com/OldBlackJoe/mybatis-mapper/blob/f15d173d01e58da392952814bf4d2bba8de86f3d/lib/convert.js#L105

Changing this from `'\\\''` to `"''"` is fixing the issue above and is the preferred way to escape the apostrophe.
Note - same behaviour if we switch language to `sql`
http://www.michael-thomas.com/tech/db2/db2_survival_guide.htm

**Comment by mavridiSS** [comment]
@OldBlackJoe any input on this?

**Comment by OldBlackJoe** [comment]
@mavridiSS
thank you for your contribution!
