### ISSUE TITLE
Dollar sign is not replaced properly

### ISSUE THREAD

**Issue by mavridiSS** [OldBlackJoe/mybatis-mapper#16]
### Prerequisites
Javascript has some replacement patterns(related to the dollar sign) when the replacement value in `String.replace` function is a string(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter)

### Issue
In our case when we try to search something with a dollar sign it is not substituted properly. Below screenshot is for reference of that behaviour.
<img width="566" alt="Screenshot 2022-05-03 at 18 04 02" src="https://user-images.githubusercontent.com/9514663/166480082-0132e3ca-e2bf-41de-b094-0009f8edeb88.png">

### Solution
Using a replacement value as a function rather than a string(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_a_parameter) because those replacement patterns won't be applied in that case

**Comment by mavridiSS** [comment]
Hi @OldBlackJoe  any input on this?

**Comment by OldBlackJoe** [comment]
hello, I'll merge it and release new version within few days.
