### ISSUE TITLE
My SQL statement was truncated.

### ISSUE THREAD

**Issue by ladmini** [OldBlackJoe/mybatis-mapper#31]
Thank you very much for bringing us such a powerful library. 
Recently, I encountered a issues while using it.

My version is as follows：
**"version": "0.6.8"**

My xml is like this:
```xml
 <select id="queryOrder">
    SELECT COUNT(*) AS orderNo FROM installation WHERE updateTime <= (
	    SELECT updateTime FROM installation WHERE deviceId = #{deviceId} AND signId = ${signId}
    ) AND signId = ${signId}
  </select>
  ```
  const sql2 = mybatisMapper.getStatement('installation_mapper', 'queryOrder', param2, sqlFormat)
  logger.debug(sql2)
  The output of the log is as follows：
  
  ```xml
  SELECT
  COUNT(*) AS orderNo
FROM
  installation
WHERE
  updateTime
  ```
  
From the above results, it can be seen that the SQL statement has been truncated, I found that the problem occurred at **<=**.
If I change **<=** to **=**, then the output will be normal.

Could you please help to check what the problem is?

**Comment by OldBlackJoe** [comment]
Hello, I think that you should use `<![CDATA[     ]]>` .

**Comment by ladmini** [comment]
@OldBlackJoe 
Thank you for your quick response! As you mentioned, after changing to `<![CDATA[     ]]>`, it works.

```xml
 <select id="queryOrder">
    SELECT COUNT(*) AS orderNo FROM installation WHERE signId = ${signId} AND <![CDATA[ updateTime <= (
	    SELECT updateTime FROM installation WHERE deviceId = #{deviceId} AND signId = ${signId}
    )]]> 
  </select>
